### ISSUE TITLE
Can this be used with three.js?

### ISSUE THREAD

**Issue by aferriss** [roboshoes/canvas-recorder#14]
Hi there, It seems like this tool is meant to provide it's own canvas context, but what about in cases where there's already an existing canvas context that I want to record? Any tips for three.js users?

Thanks!

**Comment by roboshoes** [comment]
Sorry that I totally missed this thread. 

Yes, this can be used with ThreeJS. There are two way to go about this. You can either set the canvas that `canvas-recorder` is supposed to use and take the one from Three, or the other way around, as also ThreeJS allows you to specify a canvas. 

 ```
import { options } from "canvas-recorder/gl";

// ...
const renderer = new THREE.WebGLRenderer();

options( {
    canvas: renderer.domElement,
} )
```

But if you look into Three JS documentation you can also set the canvas used by `WebGLRenderer`, similarly buy providing a canvas in the options: [WebGLRenderer Docs](https://threejs.org/docs/#api/en/renderers/WebGLRenderer)

This way you can get the canvas from canavas-recorder by calling `getCanvas()` imported like `import { getCanvas() } from "canvas-recorder/gl";`

On last thing. Anytime you use webGL make sure to import from `
"canvas-recorder/gl". It's the same API but used the webgl buffer.
